engines:
  eslint:
    enabled: true
    config:
      esversion: 6
  duplication:
    enabled: false
    config:
      languages:
      - javascript

ratings:
  paths:
  - source/**/*.js

exclude_paths:
  - source/**/*.spec.js
