language: node_js
node_js: 4.4.5

script: npm test
after_success: npm run docs && npm run coverage

deploy:
  - provider: s3
    bucket: documentation.dashaudio.co
    region: eu-west-1
    endpoint: documentation.dashaudio.co.s3-website-eu-west-1.amazonaws.com
    acl: public_read
    local_dir: build/documentation
    upload_dir: sdk/javascript
    skip_cleanup: true
    access_key_id:
      secure: ovMw4ecQtKioMzJev6KiLwyufjDz2I+ZOnBDaYqUlu4beOu8UOLwxszwNfIvrcHBmOL9Wybr75Bq7RD2NazAGmkbfUBPeO6tFUHn6An8V7eEx1sNyON5Em4VheEW34PQj51LmQOOha5LDdkBDcSyYJqULf1GvNAXvkjwmNUHGqAgjbahVrJVfBvsV1ZDOUzbrMgExQ/HbkrX6bmh2x2XTbCZ1ntLXJvhpA1Xxo7BQohxxMrFJozR9O0XyIcRW7HmdVm95FqWOvjuDhKQcynUtIS7tVz1nsij6f46bmQNXoO4VNtMGprNCiev7fod0mF0DyocciQXwg11dD2NIrEh88ENAvJu8f9C7jQyfVAFiAOO1+X3vcSLl60ef/WoBzV2ficMghqJ7QKVpytQ4S8lIEUObD+8n8PBT609nNiSFNv3wQ2thpEKWnnKC6kG41etbO12C4Fiadv6pY0CJ1hArZ1eX4wBwBs3TKHlGC3Wgw9ZQxSp/5uZZ6E74zpzfUcvPi6J2eUBMTaiteJZMbmg2LQwkatPmfl/MrgVihFcwx/Rb+p7pIgFFJPMlHxDBO5HTD4j6IRW+3mWdjcE6016snGDfqL/jJtIUo6f9K/H9U1i51CGuqu+/z5RrHnX7Sduc0/kxS3wZMgrUrwwKQ6O/QVHrCrQi7a9WR0ajlZitwo=
    secret_access_key:
      secure: xnaw/vCE3LQP0ss3LwpvDECjSAE31nvUnDHFvzRb3dJOpIHOyXZVoA6+R6XklhpEMJ98pSe+pdXOAtAD+f8P9zwH0wZQnZ4Tr5VDN1WE8ErPjMY3gFTlOrSm3ygasItNYAFuXx83qJibbkP6e1Y03Yoa+5yNFc+zOq8YxG5cMUHT2JtT9b5zTC8h1hEoaZC6u67tzcKBQLYGmldIc8GR9ln3aDUU8PdUGaXcz8kT+Ka5SlGZQCSOocS0NdqHp/42/sblLfoEGHNmM+25mrLuw8IHJR7ZOumWS0D7ma96ItesPA+N2LGfsv4d0LPmBpk5V2gXMj25RPF3iTyrq6q4capKRVinnd3zyuN+XnCv+uj6GosK1DULENAotglECPYZL+WOQNQaFGnYFrsVGHYOB5FcxRsn7lo0FgB246h6lrjgcAwb6/0lRaMN9N/2+GkhIsDltdeOksuQkZ7KVgKzivdPL7kq1PZifYs5wN1mZFoepbzC5Sn3MvUjC1rAnOXrImgZqZULKbUERfHUY0Mg01YJFm20ffQ1/S+b9D+NuwTaQzzz6gZhANbWPr1NTMng1HEiDbSiTZsj9RIceM0dc5i5FbXPzB1p2KJdJJLxBVE16xkIadvn3vUsp+biQ8LDhwsxE9HN3rWOXdZZwMzKjGix3LkUa2WiS/RaGghPVkc=
  - provider: s3
    bucket: documentation.dashaudio.co
    region: eu-west-1
    endpoint: documentation.dashaudio.co.s3-website-eu-west-1.amazonaws.com
    acl: public_read
    local_dir: build/coverage/lcov-report
    upload_dir: sdk/javascript/coverage
    skip_cleanup: true
    access_key_id:
      secure: ovMw4ecQtKioMzJev6KiLwyufjDz2I+ZOnBDaYqUlu4beOu8UOLwxszwNfIvrcHBmOL9Wybr75Bq7RD2NazAGmkbfUBPeO6tFUHn6An8V7eEx1sNyON5Em4VheEW34PQj51LmQOOha5LDdkBDcSyYJqULf1GvNAXvkjwmNUHGqAgjbahVrJVfBvsV1ZDOUzbrMgExQ/HbkrX6bmh2x2XTbCZ1ntLXJvhpA1Xxo7BQohxxMrFJozR9O0XyIcRW7HmdVm95FqWOvjuDhKQcynUtIS7tVz1nsij6f46bmQNXoO4VNtMGprNCiev7fod0mF0DyocciQXwg11dD2NIrEh88ENAvJu8f9C7jQyfVAFiAOO1+X3vcSLl60ef/WoBzV2ficMghqJ7QKVpytQ4S8lIEUObD+8n8PBT609nNiSFNv3wQ2thpEKWnnKC6kG41etbO12C4Fiadv6pY0CJ1hArZ1eX4wBwBs3TKHlGC3Wgw9ZQxSp/5uZZ6E74zpzfUcvPi6J2eUBMTaiteJZMbmg2LQwkatPmfl/MrgVihFcwx/Rb+p7pIgFFJPMlHxDBO5HTD4j6IRW+3mWdjcE6016snGDfqL/jJtIUo6f9K/H9U1i51CGuqu+/z5RrHnX7Sduc0/kxS3wZMgrUrwwKQ6O/QVHrCrQi7a9WR0ajlZitwo=
    secret_access_key:
      secure: xnaw/vCE3LQP0ss3LwpvDECjSAE31nvUnDHFvzRb3dJOpIHOyXZVoA6+R6XklhpEMJ98pSe+pdXOAtAD+f8P9zwH0wZQnZ4Tr5VDN1WE8ErPjMY3gFTlOrSm3ygasItNYAFuXx83qJibbkP6e1Y03Yoa+5yNFc+zOq8YxG5cMUHT2JtT9b5zTC8h1hEoaZC6u67tzcKBQLYGmldIc8GR9ln3aDUU8PdUGaXcz8kT+Ka5SlGZQCSOocS0NdqHp/42/sblLfoEGHNmM+25mrLuw8IHJR7ZOumWS0D7ma96ItesPA+N2LGfsv4d0LPmBpk5V2gXMj25RPF3iTyrq6q4capKRVinnd3zyuN+XnCv+uj6GosK1DULENAotglECPYZL+WOQNQaFGnYFrsVGHYOB5FcxRsn7lo0FgB246h6lrjgcAwb6/0lRaMN9N/2+GkhIsDltdeOksuQkZ7KVgKzivdPL7kq1PZifYs5wN1mZFoepbzC5Sn3MvUjC1rAnOXrImgZqZULKbUERfHUY0Mg01YJFm20ffQ1/S+b9D+NuwTaQzzz6gZhANbWPr1NTMng1HEiDbSiTZsj9RIceM0dc5i5FbXPzB1p2KJdJJLxBVE16xkIadvn3vUsp+biQ8LDhwsxE9HN3rWOXdZZwMzKjGix3LkUa2WiS/RaGghPVkc=

addons:
  code_climate:
    repo_token:
      secure: cqAL/JJi5fwvYcirTL2KAcxdodKmjlfJ4VkfWh1Yd8nXIklNyz3fm86Dj3sWrEtdFJUgmrgCzgRK9D6u3rmwdBNrfzkJM6xgVb1N923X0bK6X+QFlylpooBj41aYPzCH/puXUFFOYzcOYu2eq3Pz92muj7Ohn1C5cm7zd67ixgaZcwdxmdRGYFoy3mz1PuvyacGQuXdt3W+AWJLWcd/P36PBkNtvlYpURfO+fozkRImuG3wybpvsrEOrgzLwbj/epNF0GSzMJbqtMVM06+NkmGHH7zaBO9CKvgFcDyTp8e9+PypcaUQp+lini9SNtB93WTipFBMMrT25wytEt+JW0fhIuNfrwb27UMpsXIfKyR4yv6N0bqmW0nPeNGwkYBq3pulQgM+X0sHfHAB6c0BqOsr/byp5VuOFtF8sxAxhrdYGp19xfk6YLUnELFyHYdKIPhOFrsiQv0EtVui0DV91oogfBzt2KDgiEERkv7WC7927zzv9+bw5xGj2Z26VgVVS1aIdSBCyT/O9K3cyu9Rpy3gvJxmJFS1ic/FM/CKIYGRisuzBnT9/t/CgGclSPvMIkSE6TL04pnXt+aGZJlGFjTPM4s6H/zYwJQ7UBsGwKKpBg3bd/WeU7Sjk/WzqT2LhzbSJdCxe5d6+Um+sGhVYYx1c9d+38e/JniXYgsE7UZU=
