language: node_js
node_js: 4.4.5

script: npm test
after_success: npm run docs && npm run coverage

deploy:
  - provider: s3
    bucket: documentation.dashaudio.co
    region: eu-west-1
    endpoint: documentation.dashaudio.co.s3-website-eu-west-1.amazonaws.com
    acl: public_read
    local_dir: build/documentation
    upload_dir: sdk/javascript
    skip_cleanup: true
    access_key_id:
      secure: ovMw4ecQtKioMzJev6KiLwyufjDz2I+ZOnBDaYqUlu4beOu8UOLwxszwNfIvrcHBmOL9Wybr75Bq7RD2NazAGmkbfUBPeO6tFUHn6An8V7eEx1sNyON5Em4VheEW34PQj51LmQOOha5LDdkBDcSyYJqULf1GvNAXvkjwmNUHGqAgjbahVrJVfBvsV1ZDOUzbrMgExQ/HbkrX6bmh2x2XTbCZ1ntLXJvhpA1Xxo7BQohxxMrFJozR9O0XyIcRW7HmdVm95FqWOvjuDhKQcynUtIS7tVz1nsij6f46bmQNXoO4VNtMGprNCiev7fod0mF0DyocciQXwg11dD2NIrEh88ENAvJu8f9C7jQyfVAFiAOO1+X3vcSLl60ef/WoBzV2ficMghqJ7QKVpytQ4S8lIEUObD+8n8PBT609nNiSFNv3wQ2thpEKWnnKC6kG41etbO12C4Fiadv6pY0CJ1hArZ1eX4wBwBs3TKHlGC3Wgw9ZQxSp/5uZZ6E74zpzfUcvPi6J2eUBMTaiteJZMbmg2LQwkatPmfl/MrgVihFcwx/Rb+p7pIgFFJPMlHxDBO5HTD4j6IRW+3mWdjcE6016snGDfqL/jJtIUo6f9K/H9U1i51CGuqu+/z5RrHnX7Sduc0/kxS3wZMgrUrwwKQ6O/QVHrCrQi7a9WR0ajlZitwo=
    secret_access_key:
      secure: xnaw/vCE3LQP0ss3LwpvDECjSAE31nvUnDHFvzRb3dJOpIHOyXZVoA6+R6XklhpEMJ98pSe+pdXOAtAD+f8P9zwH0wZQnZ4Tr5VDN1WE8ErPjMY3gFTlOrSm3ygasItNYAFuXx83qJibbkP6e1Y03Yoa+5yNFc+zOq8YxG5cMUHT2JtT9b5zTC8h1hEoaZC6u67tzcKBQLYGmldIc8GR9ln3aDUU8PdUGaXcz8kT+Ka5SlGZQCSOocS0NdqHp/42/sblLfoEGHNmM+25mrLuw8IHJR7ZOumWS0D7ma96ItesPA+N2LGfsv4d0LPmBpk5V2gXMj25RPF3iTyrq6q4capKRVinnd3zyuN+XnCv+uj6GosK1DULENAotglECPYZL+WOQNQaFGnYFrsVGHYOB5FcxRsn7lo0FgB246h6lrjgcAwb6/0lRaMN9N/2+GkhIsDltdeOksuQkZ7KVgKzivdPL7kq1PZifYs5wN1mZFoepbzC5Sn3MvUjC1rAnOXrImgZqZULKbUERfHUY0Mg01YJFm20ffQ1/S+b9D+NuwTaQzzz6gZhANbWPr1NTMng1HEiDbSiTZsj9RIceM0dc5i5FbXPzB1p2KJdJJLxBVE16xkIadvn3vUsp+biQ8LDhwsxE9HN3rWOXdZZwMzKjGix3LkUa2WiS/RaGghPVkc=
  - provider: s3
    bucket: documentation.dashaudio.co
    region: eu-west-1
    endpoint: documentation.dashaudio.co.s3-website-eu-west-1.amazonaws.com
    acl: public_read
    local_dir: build/coverage/lcov-report
    upload_dir: sdk/javascript/coverage
    skip_cleanup: true
    access_key_id:
      secure: ovMw4ecQtKioMzJev6KiLwyufjDz2I+ZOnBDaYqUlu4beOu8UOLwxszwNfIvrcHBmOL9Wybr75Bq7RD2NazAGmkbfUBPeO6tFUHn6An8V7eEx1sNyON5Em4VheEW34PQj51LmQOOha5LDdkBDcSyYJqULf1GvNAXvkjwmNUHGqAgjbahVrJVfBvsV1ZDOUzbrMgExQ/HbkrX6bmh2x2XTbCZ1ntLXJvhpA1Xxo7BQohxxMrFJozR9O0XyIcRW7HmdVm95FqWOvjuDhKQcynUtIS7tVz1nsij6f46bmQNXoO4VNtMGprNCiev7fod0mF0DyocciQXwg11dD2NIrEh88ENAvJu8f9C7jQyfVAFiAOO1+X3vcSLl60ef/WoBzV2ficMghqJ7QKVpytQ4S8lIEUObD+8n8PBT609nNiSFNv3wQ2thpEKWnnKC6kG41etbO12C4Fiadv6pY0CJ1hArZ1eX4wBwBs3TKHlGC3Wgw9ZQxSp/5uZZ6E74zpzfUcvPi6J2eUBMTaiteJZMbmg2LQwkatPmfl/MrgVihFcwx/Rb+p7pIgFFJPMlHxDBO5HTD4j6IRW+3mWdjcE6016snGDfqL/jJtIUo6f9K/H9U1i51CGuqu+/z5RrHnX7Sduc0/kxS3wZMgrUrwwKQ6O/QVHrCrQi7a9WR0ajlZitwo=
    secret_access_key:
      secure: xnaw/vCE3LQP0ss3LwpvDECjSAE31nvUnDHFvzRb3dJOpIHOyXZVoA6+R6XklhpEMJ98pSe+pdXOAtAD+f8P9zwH0wZQnZ4Tr5VDN1WE8ErPjMY3gFTlOrSm3ygasItNYAFuXx83qJibbkP6e1Y03Yoa+5yNFc+zOq8YxG5cMUHT2JtT9b5zTC8h1hEoaZC6u67tzcKBQLYGmldIc8GR9ln3aDUU8PdUGaXcz8kT+Ka5SlGZQCSOocS0NdqHp/42/sblLfoEGHNmM+25mrLuw8IHJR7ZOumWS0D7ma96ItesPA+N2LGfsv4d0LPmBpk5V2gXMj25RPF3iTyrq6q4capKRVinnd3zyuN+XnCv+uj6GosK1DULENAotglECPYZL+WOQNQaFGnYFrsVGHYOB5FcxRsn7lo0FgB246h6lrjgcAwb6/0lRaMN9N/2+GkhIsDltdeOksuQkZ7KVgKzivdPL7kq1PZifYs5wN1mZFoepbzC5Sn3MvUjC1rAnOXrImgZqZULKbUERfHUY0Mg01YJFm20ffQ1/S+b9D+NuwTaQzzz6gZhANbWPr1NTMng1HEiDbSiTZsj9RIceM0dc5i5FbXPzB1p2KJdJJLxBVE16xkIadvn3vUsp+biQ8LDhwsxE9HN3rWOXdZZwMzKjGix3LkUa2WiS/RaGghPVkc=

addons:
  code_climate:
    repo_token:
      secure: wKpePiWm18N4mK2q6Gz2Jk7/NBqeNVPpuxGrGe4fMds+bcuygPq5gya7lMHVt2kOSqb4bEIohPQufZQ0Tw+OtMPYfiNbS6GfSzwdL/N1Gr1aGTXbX1KJYasBm0ZHKueuOwjiVT8bM+xVPcd9wtWFWXnUrg0U3LAPNN4W4NSHBS+R3OIpHwaXy+6Q9VaEhs5xLOOA+ToKhblEjDfXOP5XbONWpEDXIKIeqTQHI5I7tQr6DsW2kRSsxoL61oMwjQWYjnNROykLvhGmZ+3GoGmEoptsf+GSi5mTbd5ITVMWuZIryoMs1vXrUlNUER8h6d0W0WWJhjxVFJIeKHm1+w6+/nzarCC+bHqs4ScKeO2nmvGXw6eTM8gD9Xsufl6eyNMKDA1UlxOxf9xkD2yWD0EcbjwDNulXbffcT0aIiODMdk6xvU/H6P8aIzD0AGjOx0btgiqt/BQoJJKGfPhf050rlsXy4+dJEEf57dn7JKAbXfUWN5ZfKHsPBCsbb+TsNiiTJa5Qg6BmyBa9pCw2nJHJkK4nz0NXm+aasdTpLOjQY1BBhNO4Rd/Mf2LgEC7LrHTpQQMtfpSGndRRLa4YSWQLMf8Zr06S1Kgiyq345ZcNfjja/N6Pg7gq4fJrJojbv6DHXqxIjzxvYRMPw3770uxxbkkWEBBfiJHtrnIQM7loNjQ=
