language: node_js
node_js: 4.4.5

script: npm test && npm run docs

deploy:
  provider: s3
  bucket: documentation.dashaudio.co
  region: eu-west-1
  endpoint: documentation.dashaudio.co.s3-website-eu-west-1.amazonaws.com
  acl: public_read
  local_dir: build/documentation
  upload_dir: sdk/javascript
  skip_cleanup: true
  access_key_id:
    secure: "r+bbPkWAXcVvZDh8nmYLf1o+1hgt+3JccAO4fKbAhMxtKR10qCA6inlLfg6DpLhtg0nO4wB0M83YJZfhTPDm5CQc1QMvNmDM03MZbUQJkefoCK/vTwoFJ2NCxGA/xA42HuKdnOpGbkzrrya6rlcwxhWqEwafrjTmqiiw1RrusMLnBrF9mM4HAYuukN+k5kPNwLvAPegVSU4EkDtt05062vcNSkjigJdEeEeEWHZGWXQ775n2W58pGLqTIuk5gpFwwM8XR67DspsybDakQSpxO4zFJ161xNk+Ixg6G48vVfvWK/D55MmIuCT5hfoOWf8Z7XfxntBUd9Y+ijQfICiHmM46CQiGXR38rZTKAqSnUBkVYFa8FiyLYKIfGkjDftOJ8TshfcPqDvhav++Qhp0+Wh5dayX5LZVMATNtn+xDbArRN7zAQYPjxgqq+e98kBb2/lb7XATtHSGTn0zU8J2uoBErBgLRqz/YgUBKiDB1G6nAT30oXaz7AI/E52NLtijp7PiCCPh7epuvf3BC5XHHFtWO5gICOg9C8iewBeP5u08TadbWeD+JToIzYek6mt21izh/PxykNVYXA3jKjWgkl1kqXrOrVOi7uHDca7PEDG3gBc63p2WsXWXQsQyQGpdjEWbmF7OWWa1WGHKa3jJRpuLhGb/i24FfwTP4DDkEDFc="
  secret_access_key:
    secure: "XUu2+zgeUsY0X2zg44w90R3Ji3S1BQiLUwTtJQz8fTDH739M8JVvs01lZcCwALugPC5kGLLH+pUhlc16JSW6LUPInWh4rnkDO57H3NPJvRDBya7iaREirhxoPLyyhf87hk0hjXLPR2nZ5aIHQPw932sSisg7OrjYIucCEeb3cLZ8Ur+RwrBgNWUCHYWDFm70KZ71417nuqepzcA+acD77PNZdZ3OnkTCdZ8t+3ZsoGfXgz6wtzcME1tRIK3tkv7CMzkYUe5Z44x/AHNpMQBu/oZYawHB5PUmyZWkteEVRBYX1mIXWSd3LK9XK1VEcWeNSJIzIGi4EL3ZxmQJkbHszemjeeA/M5TQMouYQtZCY+Fn91eMk8SBTesjvizxM7PDeAkk31V74bw3ikOTK49QMryqCe6WZ7l7dSwHgNJ4UdfkzjrWCmzO9vJWyC0qNx71Uk6H674WLA2zcGxCO+QpjClEElgpuYPos58x18Kro1Wl8OcJEYY4iMCsNQtlTofxtoOZC7NmDF1eLLf2DQFRVJVW8wzemRhQmQTluEtcX7miJMpAwVkFsYsVh87aTolU4WN2HAJUdZ1DGrYrK590WlrCEcApwacTAG+bPqt37nfYcBjEDXuflLyFa5ua7PrHjzY4n7UntKq/KlcuY6Tj7e20MVYCBEmCd4xQNFtY2Xs="
