language: node_js
node_js: 4.4.5

script:
  - npm test
  - npm run build

after_success:
  - npm run coverage
  - npm run docs

deploy:
  - provider: s3
    bucket: documentation.dashaudio.co
    region: eu-west-1
    acl: public_read
    local_dir: build/documentation
    upload_dir: sdk/javascript
    skip_cleanup: true
    access_key_id:
      secure: ovMw4ecQtKioMzJev6KiLwyufjDz2I+ZOnBDaYqUlu4beOu8UOLwxszwNfIvrcHBmOL9Wybr75Bq7RD2NazAGmkbfUBPeO6tFUHn6An8V7eEx1sNyON5Em4VheEW34PQj51LmQOOha5LDdkBDcSyYJqULf1GvNAXvkjwmNUHGqAgjbahVrJVfBvsV1ZDOUzbrMgExQ/HbkrX6bmh2x2XTbCZ1ntLXJvhpA1Xxo7BQohxxMrFJozR9O0XyIcRW7HmdVm95FqWOvjuDhKQcynUtIS7tVz1nsij6f46bmQNXoO4VNtMGprNCiev7fod0mF0DyocciQXwg11dD2NIrEh88ENAvJu8f9C7jQyfVAFiAOO1+X3vcSLl60ef/WoBzV2ficMghqJ7QKVpytQ4S8lIEUObD+8n8PBT609nNiSFNv3wQ2thpEKWnnKC6kG41etbO12C4Fiadv6pY0CJ1hArZ1eX4wBwBs3TKHlGC3Wgw9ZQxSp/5uZZ6E74zpzfUcvPi6J2eUBMTaiteJZMbmg2LQwkatPmfl/MrgVihFcwx/Rb+p7pIgFFJPMlHxDBO5HTD4j6IRW+3mWdjcE6016snGDfqL/jJtIUo6f9K/H9U1i51CGuqu+/z5RrHnX7Sduc0/kxS3wZMgrUrwwKQ6O/QVHrCrQi7a9WR0ajlZitwo=
    secret_access_key:
      secure: xnaw/vCE3LQP0ss3LwpvDECjSAE31nvUnDHFvzRb3dJOpIHOyXZVoA6+R6XklhpEMJ98pSe+pdXOAtAD+f8P9zwH0wZQnZ4Tr5VDN1WE8ErPjMY3gFTlOrSm3ygasItNYAFuXx83qJibbkP6e1Y03Yoa+5yNFc+zOq8YxG5cMUHT2JtT9b5zTC8h1hEoaZC6u67tzcKBQLYGmldIc8GR9ln3aDUU8PdUGaXcz8kT+Ka5SlGZQCSOocS0NdqHp/42/sblLfoEGHNmM+25mrLuw8IHJR7ZOumWS0D7ma96ItesPA+N2LGfsv4d0LPmBpk5V2gXMj25RPF3iTyrq6q4capKRVinnd3zyuN+XnCv+uj6GosK1DULENAotglECPYZL+WOQNQaFGnYFrsVGHYOB5FcxRsn7lo0FgB246h6lrjgcAwb6/0lRaMN9N/2+GkhIsDltdeOksuQkZ7KVgKzivdPL7kq1PZifYs5wN1mZFoepbzC5Sn3MvUjC1rAnOXrImgZqZULKbUERfHUY0Mg01YJFm20ffQ1/S+b9D+NuwTaQzzz6gZhANbWPr1NTMng1HEiDbSiTZsj9RIceM0dc5i5FbXPzB1p2KJdJJLxBVE16xkIadvn3vUsp+biQ8LDhwsxE9HN3rWOXdZZwMzKjGix3LkUa2WiS/RaGghPVkc=
  - provider: npm
    skip_cleanup: true
    email:
      secure: OHovLm2HUjLTQ1t7Jko3aCBieuR9yZr5e1TfPySUZ7ptg6XVJfPoNRBVCxvyvdpiTOJq+TDfBMRxb8QovdFA9T0AHv5IsIEjCy9Leb5wfFLq7czBzvuUB9c8JTxO4zlKoDf8VYIzIfAWxP6rLYJ3Jqh0giUFgejLPfxh7xdQPmCBJsaxds11T3qYT7R7O/ZhrffGt3M6rkwcv2tCGJcYozxY/VkjtRqcwMjzeAA6FyliHhA2ZesLXQJNgy1WXFMM3qPu7efXiB9kgSLnNrGFZJ6DYGbVSmnap124oKrxMJsHOV4EVZzTKEoPvKEwhxVqwvb3F4UaOe6vISpGL26ag9Qu1qygTbOjhBVkaqHZDaz+/thEbfsWScCF0gCBNC6IYflOcae+NXdKsNjAsuqFHpZgc3TVT5OFdGQbH662wnexZQ1u9ZXTUJc+kWDSKCjbQc12HLz4SU8SVJANVCRF1m+jk1McJzhVWWCFF4WSEj696ZViA6F8Gje+aZFm1OzSwcV4uBEQRSnWpmEi+vZWEDqBuXwCVh446fHYKb0JLxqpaJJq/RWUXXXNN8SLdW/YTbYRvCqm6Lch++WAcEOJpV5G2GfQH5AQBIAgiDOBDbAfB++6EUZnNhHhuY+Vdu8d7RXZNuwPjMGFDi1std0BgWF1gw34XyXen66xv7pPAXw=
    api_key:
      secure: pdhi5UDlmoI9ZKBgf140BiK/6CnR6mrT/tkg/l8dEiz1aAn6NdNEzmXiM2sMY9scZeexIxph7E1XsqW0XIEaprSYtR+6jRZFhX1XkyIwmsErF9Nq0l4Ca0Cc53XbSXeOc4tMNVHJ53p9LIvIGWNamrVmGe8I+6w5N7VfxXDNBsxQ0VZ7pSKg1+JIXkf3N5CsZ7fHIvdh/kBpO5Ut7MJr9t1R5W5nqzMvcuCIOpmSeKOzJh3TWgFF/BIP6eXElGSfpzHV1uEDS4RDcinHVf9G0qJLCiLp3SDX/gbPavf9ngun3dKk8Jk1vVRzPIqFbORnF9uMuIa5SLhpTpUdKos3hVZ4nKPvwjUKyNX6Jj81+UErnoD1V+jZ4EuVIhtC2HBdbm4drRPT4J+IWA6/fP57FpOLh67fDwvBpRzYkYltiXt4uSjlj18UNKmpwn1kOoctQgdTIOeIl1DwgSBg1oPHS5f+4lvpN8vXXkEmFS9w4xVqf9lTTFjUu1ZFxDTnaeg6BQlQpnuZ47sve8VnjBFU11mOsVgpHEkdd7r/oD5TyaC9kkvfyNEJfJt8/M+pvEG743f8kdK6SXpZmUbqvIk8BBuunSR4TPT9o32HkZIMdYaTcRMPZsPY1GW+FWaKX3lx8cyVcw4Lw+9ZZl+PlGiacs9QPAtel2zFMV3vTnqA6/A=
    on:
      tags: true

addons:
  code_climate:
    repo_token:
      secure: wKpePiWm18N4mK2q6Gz2Jk7/NBqeNVPpuxGrGe4fMds+bcuygPq5gya7lMHVt2kOSqb4bEIohPQufZQ0Tw+OtMPYfiNbS6GfSzwdL/N1Gr1aGTXbX1KJYasBm0ZHKueuOwjiVT8bM+xVPcd9wtWFWXnUrg0U3LAPNN4W4NSHBS+R3OIpHwaXy+6Q9VaEhs5xLOOA+ToKhblEjDfXOP5XbONWpEDXIKIeqTQHI5I7tQr6DsW2kRSsxoL61oMwjQWYjnNROykLvhGmZ+3GoGmEoptsf+GSi5mTbd5ITVMWuZIryoMs1vXrUlNUER8h6d0W0WWJhjxVFJIeKHm1+w6+/nzarCC+bHqs4ScKeO2nmvGXw6eTM8gD9Xsufl6eyNMKDA1UlxOxf9xkD2yWD0EcbjwDNulXbffcT0aIiODMdk6xvU/H6P8aIzD0AGjOx0btgiqt/BQoJJKGfPhf050rlsXy4+dJEEf57dn7JKAbXfUWN5ZfKHsPBCsbb+TsNiiTJa5Qg6BmyBa9pCw2nJHJkK4nz0NXm+aasdTpLOjQY1BBhNO4Rd/Mf2LgEC7LrHTpQQMtfpSGndRRLa4YSWQLMf8Zr06S1Kgiyq345ZcNfjja/N6Pg7gq4fJrJojbv6DHXqxIjzxvYRMPw3770uxxbkkWEBBfiJHtrnIQM7loNjQ=

notifications:
  email: false
